Добавление сессии
go-park-mail-ru/2024_1_ResCogitans pull request #11
Opened 2024-03-08 07:57 UTC by AlGrItm

2024-03-08 15:07 UTC, GeorgiyX requested changes

2024-03-08 15:07 UTC, GeorgiyX commented on internal/entities/session.go
> +	"time"
`goimport -w internal/entities/session.go`

2024-03-08 15:07 UTC, GeorgiyX commented on internal/entities/session.go
> +	userID, _ := SessionStore[cookie.Value]
Можно использовать синтаксис с одним параметром `userID := SessionStore[cookie.Value]`

2024-03-08 15:07 UTC, GeorgiyX commented on internal/entities/session.go
> +	cookie, err := r.Cookie("session_id")
`session_id` в константы

2024-03-08 15:07 UTC, GeorgiyX commented on utils/middle/sessionMiddleware.go
> +		ctx := context.WithValue(r.Context(), "userID", userID)
Вообще в качестве ключа в контексте лучше не использовать строки, а объявить свой тип:

```go
type userIDType struct {}
var userIDKey userIDType
...
ctx := context.WithValue(r.Context(), userIDKey, userID)
```

2024-03-08 15:07 UTC, GeorgiyX commented on utils/middle/sessionMiddleware.go
> +		ctx := context.WithValue(r.Context(), "userID", userID)
Иначе возможны колизии со строковым ключом

2024-03-08 15:07 UTC, GeorgiyX commented on utils/middle/sessionMiddleware.go
Имена файлов в snake_case

2024-03-08 15:07 UTC, GeorgiyX commented on internal/entities/session.go
Вроде решили, что в entities будут храниться только структуры описывающие сущности. Для реализации логики сессий нужно завести отдельный пакет например usecase. У нас есть требование к следующему РК по формировании архитектуры, так что предлагаю переделать в соответствии с чистой архитектурой.

2024-03-08 15:07 UTC, GeorgiyX commented on internal/http-server/handlers/authorization/authorization_handler.go
> -)
А почему решили отказаться от этого?

2024-03-08 15:07 UTC, GeorgiyX commented on internal/http-server/handlers/authorization/authorization_handler.go
> +		entities.SetSession(responseWriter, user.ID)
Давай все-таки будем возвращать ошибку. Если не удастся установить сессию, то на фронте нужно отобразить ошибку - т.к. нас сервис не сможет нормально работать.

2024-03-08 15:07 UTC, GeorgiyX commented on internal/http-server/handlers/authorization/authorization_handler.go
> +	request, ok := ctx.Value(httputils.HttpRequestKey).(*http.Request)
для этого есть функция `httputils.HttpRequest`

2024-03-08 15:07 UTC, GeorgiyX commented on internal/entities/session.go
> +	}
Почему тут именно `ErrNoCookie` проверяешь? Любая ошибка от `r.Cookie("session_id")` не должна пропускаться.

2024-03-08 15:07 UTC, GeorgiyX commented on internal/entities/session.go
> +	delete(SessionStore, cookie.Value)
Возможен конкуретный доступ к `SessionStore`. Нужен мьютекс (в других местах тоже)

2024-03-11 06:16 UTC, GeorgiyX commented on internal/usecase/session.go
> +	}
В предыдущих PRах писал - обычно проверяют негативный кейс (err != nil), иначе будет расти вложенность кода. Else в 34 строке не нужен, т.к. перед ним делаем return

2024-03-11 08:41 UTC, GeorgiyX commented on internal/usecase/session.go
> +	}
Если не получилось удалить из хранилища мы должны вернуть возвращаем 500ку

2024-03-14 21:15 UTC, GeorgiyX approved these changes

2024-03-14 21:15 UTC, GeorgiyX commented on internal/usecase/session.go
> +	}
Вообще хорошо бы уже сделать AuthUseCase  структурой, а SessionStore  ее полем.

2024-03-14 21:15 UTC, GeorgiyX commented on internal/http-server/handlers/authorization/authorization_handler.go
>  	}
Давай оставим валидацию, что userName и passoword не пустые. Нам нет интереса ходить в БД и тратить на это ресурсы, если мы и так можем понять, что пользователь не будет найден/аутентифицирован.

2024-03-14 21:15 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +	ctx = context.WithValue(ctx, httputils.HttpRequestKey, httpReq)
Лучше логику с ключами контекста скрыть внутри пакета httputils. Так и код проще читать (`GetRequestFromCtx(ctx context.Context) (*http.Request, bool)`/`SetRequestToCtx(ctx context.Context, r *http.Request) context.Context`) и доступ к объекту контекста возможен только через определенные в пакете функции и нигде больше.

2024-03-31 14:51 UTC, GeorgiyX requested changes

2024-03-31 14:51 UTC, GeorgiyX commented on internal/http-server/handlers/registration/registration_handler.go
> +	}
Это бизнес логика создания юзера. Она должна быть в юзкейсе.

2024-03-31 14:51 UTC, GeorgiyX commented on internal/storage/storage.go
Стоит этот файлик положить в поддиректорию: `internal/storage/session/`. Т.к. нас будет много стораджей, под каждую сущность.

2024-03-31 14:51 UTC, GeorgiyX commented on internal/storage/storage.go
> +		Store: make(map[string]int),
А мьютекс почему не инициализируется явно?

2024-03-31 14:51 UTC, GeorgiyX commented on internal/entities/user.go
>  }
Договаривались, что в пакете entities должны храниться только структуры описывающие сущности из нашей предметной области. А этот код относится к стораджу, давай его перенесем в storage пакет и тоже перепишем на структуру с методами (как

2024-03-31 14:51 UTC, GeorgiyX commented on utils/middle/session_middleware.go
> +		userID, _ := m.useCase.GetSession(r)
А почему игнорируется ошибка?

2024-04-03 13:10 UTC, AlGrItm commented on utils/middle/session_middleware.go
> +		userID, _ := m.useCase.GetSession(r)
Функция GetSession возвращаем ошибку в случае, если сессия не найдена. В данном случае я и ожидаю эту ситуацию, потому что пользователь авторизуется и у него не должно быть сессии

2024-04-05 07:48 UTC, GeorgiyX commented on utils/middle/session_middleware.go
> +		userID, _ := m.useCase.GetSession(r)
Любой метод может быть доработан кем-то и начать возвращать другие ошибки (особенно актуально если у проект большой и не все изменения разработчики могут друг с другом обсудить). Лучше в таком случае проверять проверять ошибку на равенство через errors.Is, из если ошибка допустимая (SessionNotFound), то игнорируем ее, иначе завершаемся с ошибкой. В этом случае наш код будет более устойчивым к изменениям в GetSession.

2024-04-28 17:41 UTC, closed without merging