Database
go-park-mail-ru/2024_1_ResCogitans pull request #16
Opened 2024-03-29 16:37 UTC by MrDzhofik

Добавил соединение с БД и поправил ручку получения всех достопримечательностей, чтобы она брала данные из БД. Предпринял попытку сделать чистую архитектуру

2024-04-01 07:01 UTC, GeorgiyX requested changes

2024-04-01 07:01 UTC, GeorgiyX commented on internal/repository/postgres/sight.go
> +	var Sights = []*entities.Sight{}
Имена локальных переменных должны быть в нижнем регистре - `sights `

2024-04-01 07:01 UTC, GeorgiyX commented on internal/repository/postgres/sight.go
> +	DB *sql.DB
Поле `DB` должно быть в нижнем регистре, т.е. оно не должно быть доступно вне пакета

2024-04-01 07:01 UTC, GeorgiyX commented on internal/repository/postgres/sight.go
> +func NewSightRepo(db *sql.DB, err error) *SightRepo {
А зачем в конструктор передаешь `error`?

2024-04-01 07:01 UTC, GeorgiyX commented on internal/repository/postgres/sight.go
> +	}
Пустая строка обычно не ставится между операцией и проверкой ошибки после нее.

2024-04-01 07:01 UTC, GeorgiyX commented on internal/repository/postgres/sight.go
> +func (repo *SightRepo) GetSightsList() ([]*entities.Sight, error) {
Давай возвращать просто `[]entities.Sight`

2024-04-01 07:01 UTC, GeorgiyX commented on internal/delivery/handler_test.go
> +		City_id:     "1",
Имена полей в camelCase (если поле не должно быть доступно за пределами пакета) или CamelCase (если должно быть доступно за пределами пакета).

2024-04-01 07:01 UTC, GeorgiyX commented on internal/http-server/server/db/db.go
> +	)
Давай эти параметры вынесем в конфиг

2024-04-01 07:01 UTC, GeorgiyX commented on internal/http-server/server/db/db.go
> +	db.SetMaxOpenConns(10)
Обычно с драйвером pgx используют собственную реализацию пула - pgxpool (она более специфичная и работает [лучше](https://github.com/jackc/pgx#choosing-between-the-pgx-and-databasesql-interfaces)). Давай будем использовать ее.

2024-04-01 07:01 UTC, GeorgiyX commented on internal/repository/postgres/sight.go
> +	err = rows.Err()
Для превращения строк в слайс структур можно использовать [`scany`](https://github.com/georgysavva/scany). Это сильно сократит объем рутинного кода.

2024-04-01 07:01 UTC, GeorgiyX commented on internal/repository/postgres/sight.go
> +	if err != nil && err != sql.ErrNoRows {
Ошибки на равенство обычно проверяют через `errors.Is`, а не через `==` (эта функция учитывает, что ошибка может быть "обернута" через `errors.Wrap`)

2024-04-01 07:01 UTC, GeorgiyX commented on internal/usecase/session.go
Вроде сессисии рефакторим в этом PR (https://github.com/go-park-mail-ru/2024_1_ResCogitans/pull/15)?

2024-04-01 07:01 UTC, GeorgiyX commented on internal/delivery/handler.go
> +	}
В хендлере нужно вызывать юзекейс. А вот юзкейс уже ответственен за походы в стораджи.

2024-04-01 07:01 UTC, GeorgiyX commented on internal/delivery/handler.go
> +func (h *SightsHandler) GetSights(ctx context.Context, _ entities.Sight) (Sights, error) {
Давай заведем тип `Empty`на случай если у хендлера нет данных в запросе

2024-04-01 07:01 UTC, GeorgiyX commented on internal/delivery/handler.go
> +	sightsRepo := sightRep.NewSightRepo(db.GetPostgres())
Репозиторий (сторадж) должен инициализироваться в main функции, как и коннект к БД

2024-04-01 07:01 UTC, GeorgiyX commented on internal/delivery/handler.go
> +	}
Давай сразу возвращать `[]entities.Sight`

2024-04-01 07:01 UTC, GeorgiyX commented on internal/delivery/handler.go
> +
Юзкейс нужно вынести в отдельный пакет

2024-04-01 07:01 UTC, GeorgiyX commented on internal/delivery/handler.go
> +type SightsHandler struct{}
У хендлера должно быть поле с юзкейсом. Его будем передавать при инициализации в main

2024-04-01 07:29 UTC, GeorgiyX commented
@MrDzhofik привет, давай будем sql хранить в виде миграций, т.е. последовательных изменений БД (для этого нужно разместить код в пронумерованных файликах в одной директории, например `migrations`). Для выполнений миграций можно использовать [goose](https://github.com/pressly/goose) - там найдешь подробности по формату файлов.

2024-04-01 14:38 UTC, MrDzhofik commented on internal/usecase/session.go
Да, в ветке session, тут я их не трогал

2024-04-01 14:42 UTC, MrDzhofik commented on internal/delivery/handler.go
> +func (h *SightsHandler) GetSights(ctx context.Context, _ entities.Sight) (Sights, error) {
Вот тут не совсем понял

2024-04-01 14:45 UTC, MrDzhofik commented on internal/delivery/handler.go
> +	sightsRepo := sightRep.NewSightRepo(db.GetPostgres())
Я смотрел в репозиториях прошлых лет, там были сервисы по типу UserService и SightService и у каждого свой main. Я подумал, что это относится к микросервисам, про которые нам расскажут в среду. Мне так надо сделать?

2024-04-25 05:10 UTC, GeorgiyX requested changes

2024-04-25 05:10 UTC, GeorgiyX commented on sql/create_tables/sight.sql
> +	-- },
Что-то лишнее

2024-04-25 05:10 UTC, GeorgiyX commented on sql/create_tables/country.sql
> +    name text NOT NULL
Давай добавим ограничение уникальности на это поле

2024-04-25 05:10 UTC, GeorgiyX commented on internal/config/config.go
> +}
Нужно поднять собственный редиc (можно прям в контейнере через docker compose). 
Можно взять имадж [bitnami/redis](https://hub.docker.com/r/bitnami/redis), в описание есть пример конфига для docker compose.

2024-04-25 05:10 UTC, GeorgiyX commented on internal/config/config.go
> +}
Пароли в репозиторий пушить не стоит

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/db/db.go
> +}
Давайте конфиг базы и редиса будем передавать снаружи

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/handlers/authorization/auth_handler_test.go
Если это не используется - удаляйте файл

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/handlers/avatar/avatar.go
> +	uploadPath := filepath.Join(cwd, "../../../Modules/public", header.Filename)
Передавайте через конфиг и желательно полным путем

2024-04-25 05:10 UTC, GeorgiyX commented on docker/Dockerfile
Кажется, что нет необходимости в этом Dockerfile. Все что тут делается можно выполнить со стандартным контейнером через передачу переменных окружения и монтирования директории с `init.sql`

```
volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
```

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/db/db.go
> +}
Давайте конфиги передавать снаружи

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/file.go
> +	r.ParseMultipartForm(10 << 20)
ParseMultipartForm может вернуть ошибку, нужно ее обработать

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/file.go
> +func ValidateFileSize(handler *multipart.FileHeader) bool {
Похоже эта функция нам не нужна за пределами пакета, в таком случае нужно сделать ее не экспортируемой

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/file.go
> +}
В `net/http` для этого есть функа `http.DetectContentType()`

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/file.go
> +		return string(""), err
Можно просто вернуть `""`

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/file.go
> +		logger.Error("Error while creating file:", "error", err)
Лучше добавить это инфу к самой ошибке: 
```go
err = errors.Wrap(err, "error while creating file")
logger.Error(errr)
return "", err
```

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/file.go
> +	targetFile, err := os.Create(cfg.FileUploadPath + handler.Filename)
При сохранении файла нужно выдавать ему новое уникальное имя. Иначе у пользователей будет возможность менять чужие аватарки через подбор имени файла

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/file.go
> +	targetFile, err := os.Create(cfg.FileUploadPath + handler.Filename)
А cfg.FileUploadPath точно всегда будет оканчиваться на "/"? Тут нужно использовать `filepath.Join`

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/file.go
> +	targetFile, err := os.Create(cfg.FileUploadPath + handler.Filename)
Плюс расширение файла нужно определять через mime type (`mime.ExtensionsByType()`)

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/handlers/avatar/avatar.go
> +}
Давайте удалим эту функу, т.к. уже есть `ProfileHandler.UploadFile`

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/handlers/avatar/avatar.go
> +}
А то сейчас бек работает как бесплатный файлообменник

2024-04-25 05:10 UTC, GeorgiyX commented on cmd/2024_1_ResCogitans/main.go
> +	pdb, rdb, err := initialization.DataBaseIniInitialization()
Давайте отдельно инициализировать базу и редис

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/handlers/profile/profile_handler.go
> +	_, _ = w.Write(rawJSON)
Не вижу проверки авторизации

2024-04-25 05:10 UTC, GeorgiyX commented on internal/delivery/handlers/registration/registration_handler.go
> +		}
Почему такое условие? Если  `"Cookie not found"`, то нужно вернуть bad request и т.д...

2024-04-25 05:12 UTC, GeorgiyX commented on internal/delivery/handlers/comment/comment.go
> +	dataInt["rating"] = requestData.Rating
Давате использовать структуры)

2024-04-27 08:00 UTC, GeorgiyX commented on internal/delivery/handlers/registration/registration_handler.go
> +		}
Давай сделаем в sessionUseCase метод `IsAuthorized` и тут будем проверять лишь bool

2024-05-18 09:06 UTC, GeorgiyX requested changes

2024-05-18 09:06 UTC, GeorgiyX commented on internal/storage/redis/csrf/csrf_storage.go
> +	}()
Контекст нужно снаружи передавать из main функции

2024-05-18 09:06 UTC, GeorgiyX commented on internal/usecase/csrf_usecase.go
> +}
@AlGrItm CSRF токен должен передаваться строго не в куки, в этом и его смысл. Токен должен нас защитить от атаки при которой с сайта злоумышленника отправляется запрос на jantugan (через тег form) вместе с куками нашего сайта. Но если мы защищаемся от такой атаки, мы помимо авторизации в куках будем еще искать проверять CSRF токен, переданный в заголовках запроса (т.е. такой токен не должен отправляться автоматически).

2024-05-18 09:06 UTC, GeorgiyX commented on internal/usecase/csrf_usecase.go
> +}
Вот [тут](https://maddevs.io/blog/web-security-an-overview-of-sop-cors-and-csrf/) можно почитать подробнее

2024-05-18 09:06 UTC, GeorgiyX commented on utils/middle/session_middleware.go
> +			token := r.Header.Get("X-CSRF-Token")
@AlGrItm  Вижу что ожидаешь токен в заголовке, но почему передаешь его в куке?

2024-05-18 09:06 UTC, GeorgiyX commented on internal/storage/postgres/user/user_profile_storage.go
> +	}
@AlGrItm  Контекст нужно передавать в каждый запрос (GetUserProfileByID, EditUsername и т.д.) снаружи (фактически это будет контекст который вы достаете во враппере), это позволит например отменять запросы и освобождать коннекты как только будет отменен запрос от клиента.

2024-05-18 09:06 UTC, GeorgiyX commented on internal/storage/postgres/user/user_profile_storage.go
> +	}
И в других местах это тоже стоит исправить

2024-05-18 09:06 UTC, GeorgiyX commented on internal/storage/postgres/user/user_storage.go
> +	defer us.mu.Unlock()
Зачем тут мьютекс? Постгрес сам обеспечит безопасный конкурентный доступ.

2024-05-18 09:06 UTC, GeorgiyX commented on internal/storage/redis/csrf/csrf_storage.go
> +	defer cs.mu.Unlock()
@AlGrItm  Тут тоже мьютекс не нужен

2024-05-18 09:06 UTC, GeorgiyX commented on internal/storage/redis/csrf/csrf_storage.go
> +	defer cs.mu.Unlock()
И в других местах тоже

2024-05-18 09:06 UTC, GeorgiyX commented on internal/storage/postgres/question/question_storage.go
> +	ctx := context.Background()
Контекст нужно передавать снаружи

2024-05-23 15:15 UTC, GeorgiyX commented on internal/storage/redis/csrf/csrf_storage.go
> +	}()
Хотя именно тут он вообще не нужен, давай добавим контекст только как параметр в методах

2024-05-25 01:26 UTC, GeorgiyX approved these changes

2024-05-26 08:40 UTC, merged