Map integration
go-park-mail-ru/2024_1_ResCogitans pull request #23
Opened 2024-04-29 08:27 UTC by MrDzhofik

Добавил геоданые для интеграции с картой 
Начал тесты править, чтобы они заработали
Изменил загрузку аватарок, но она пока тоже не работает

2024-05-05 15:46 UTC, GeorgiyX requested changes

2024-05-05 15:46 UTC, GeorgiyX commented on db/migrations/20240401145225_create_and_insert_tables.sql
В соседнем PR оставил замечание - новые изменения над схемой БД нужно делать в отдельных миграциях.

https://github.com/go-park-mail-ru/2024_1_ResCogitans/pull/22#discussion_r1590323813
https://github.com/go-park-mail-ru/2024_1_ResCogitans/pull/22#discussion_r1590327255

2024-05-05 15:46 UTC, GeorgiyX commented on db/migrations/20240401145225_create_and_insert_tables.sql
> +    longitude   double precision,
Может стоит сделать поле not null?

2024-05-05 15:46 UTC, GeorgiyX commented on db/migrations/20240401145225_create_and_insert_tables.sql
> +    path text UNIQUE,
Имя фото должно быть уникальным, можно испльзовать его как PK

2024-05-05 15:46 UTC, GeorgiyX commented on db/migrations/20240401145225_create_and_insert_tables.sql
> +    created_at timestamptz
Можно добавить `DEFAULT NOW()`

2024-05-05 15:46 UTC, GeorgiyX commented on db/migrations/20240401145225_create_and_insert_tables.sql
> +EXECUTE FUNCTION update_sight_rating();
Наверное не заметил это в предыдущих PRах, но лучше не использовать триггеры, т.к. это как минимум размазывает логику между БД беком.

2024-05-05 15:46 UTC, GeorgiyX commented on internal/delivery/file.go
> +	flag := ValidateFileExtension(*handler)
А почему не по указателю передаете в ValidateFileExtension?

2024-05-05 15:46 UTC, GeorgiyX commented on internal/delivery/handlers/album/album.go
> +func (h *AlbumHandler) DeleteAlbum(_ context.Context, album entities.Album) (entities.Album, error) {
Для удаления альбома необходимо знать только ID альбома. Давай оставим только один параметр.

2024-05-05 15:46 UTC, GeorgiyX commented on internal/delivery/handlers/album/album.go
> +	return entities.Album{}, nil
Тут не нужна проверка авторизации?

2024-05-05 15:46 UTC, GeorgiyX commented on internal/delivery/handlers/album/album.go
> +func (h *AlbumHandler) GetAlbums(ctx context.Context, _ entities.Album) (entities.Albums, error) {
Давай использовать структуру Empty если у запроса нет никаких параметров

2024-05-05 15:46 UTC, GeorgiyX commented on internal/entities/album.go
> +}
А почему никак не валидируем?

2024-05-05 15:46 UTC, GeorgiyX commented on internal/entities/sight.go
> +	Latitude    *float64 `json:"latitude"`
Подскажи почему тут указатели?

2024-05-05 15:46 UTC, GeorgiyX commented on internal/entities/sight.go
> +	Latitude    *float64 `json:"latitude"`
Если в них нет необходимости давай по значению хранить координаты

2024-05-05 15:46 UTC, GeorgiyX commented on internal/storage/postgres/album/album_storage.go
> +	ctx := context.Background()
В соседнем PR отписал насчет контекста:

https://github.com/go-park-mail-ru/2024_1_ResCogitans/pull/22#discussion_r1590328015

2024-05-05 15:46 UTC, GeorgiyX commented on internal/storage/postgres/album/album_storage.go
> +	VALUES($1, $2, $3) RETURNING id`, album.UserID, album.Name, album.Description).Scan(&albumID)
Вроде используем scany для таких целей? Там есть метод `Get`.

2024-05-05 15:46 UTC, GeorgiyX commented on internal/storage/postgres/album/album_storage.go
> +	}
Можно сразу считывать в `[]entities.Album`

2024-05-05 15:46 UTC, GeorgiyX commented on internal/delivery/handlers/album/album.go
> +	return entities.Album{}, nil
Давай также проверим что альбом с указанным albumID существует для текущего userID, чтобы пользователи не могли удалять чужие альбомы.

2024-05-05 15:46 UTC, GeorgiyX commented on internal/storage/postgres/album/album_storage.go
> +}
При удалении альбома имеет смысл также передавать userID, чтобы пользователь не мог удалить чужой альбом.

2024-05-05 15:46 UTC, GeorgiyX commented on internal/usecase/album_usecase.go
> +	return entities.Album{ID: album.ID}, nil
Давай отдавать только ID альбома, т.к. другие поля мы не заполняем.

2024-05-05 15:46 UTC, GeorgiyX commented on router/router.go
> +}
Кажется конструкция с роутером с одним путем избыточная. Давайте или возвращать настроенный роутер для всех URL управления альбомами или монтировать без вспомогательного роутера.

2024-05-05 15:46 UTC, GeorgiyX commented on utils/cors/cors.go
> +		w.Header().Set("Access-Control-Allow-Origin", "http://localhost:3000")
Чувствую на сервере приходится менять эту строчку перед запуском? Давайте брать из конфига.

2024-05-10 14:57 UTC, MrDzhofik commented on db/migrations/20240401145225_create_and_insert_tables.sql
Давай перейдем на другой PR, а этот оставим

2024-05-10 14:58 UTC, closed without merging