Http handler wrapper
go-park-mail-ru/2024_1_ResCogitans pull request #3
Opened 2024-03-01 22:56 UTC by sp20ks

**Парсить GET параметры и path параметры (параметры, которые вы указывайте шаблоном в url роутера) и класть их в контекст.** - пока не сделано

Анмаршалить body запроса в структуру.

Маршалить структуру ответа и записывать ее в http.ResponseWriter

В случае ошибки отсылать JSON с деталями ошибки и статус кодом.

Логгировать детали ошибки.

Устанавливать лимиты на чтение body запроса

Валидировать данные запроса (для этого структура запроса может имплементить интерфейс с методом func Validate() error)

2024-03-03 23:31 UTC, GeorgiyX requested changes

2024-03-03 23:31 UTC, GeorgiyX commented on utils/logger/logger.go
> +	}
Давайте вместо ошибки просто использовать уровень логгирования по умолчанию. И выводить сообщение об ошибке.

2024-03-03 23:31 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +		}
А почему `Validate` на хенделере вызывается? Validate нужно вызвать на структуре, описывающей данные, которые мы ожидаем в запросе. Для этого нам и нужен шаблонный параметр у `HandlerWrapper`.

Т.е. одна из задач этой обертки:
1. Создать структуру описывающую данные из запроса. Для этого нужен соответствующий шаблонный параметр у HandlerWrapper'a. 
2. Заанмаршалить body запроса в эту структуру.
3. Вызвать `Validate()` на структуре из п.1. Если валидация не успешна - вернуть bad request. Для того чтобы можно было вызвать Validate, мы определяем ограничение для шаблонного типа в виде интерфейса с единственным методом `Validate`. 
4. Передать провалидированную стуктуру из п.1 в обработчик запроса (хендлер).
5. Получить от хендлера структуру с данными респонса или ошибку. Структура с данными респонса это тоже шаблонный тип, не интерфейс.
6. Замаршалить в байты структуру ответа, записать ответ и статус код.

2024-03-03 23:31 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +		}
Давай это в отдельную функцию вынесем `GetPathParams`

2024-03-04 07:35 UTC, GeorgiyX requested changes

2024-03-04 07:35 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +		}
Лучше path параметры сохранить как есть (мапкой) по ключу requestPathParams. Иначе при таком подходе есть вероятность, что ключи могут конфликтовать

2024-03-04 07:35 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +		response, err := handler.ServeHTTP(ctx, w, r)
Давай в хендлер передавать не request (`r`), а распаршенный json запроса - `requestData`.

2024-03-04 07:35 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +	ServeHTTP(context.Context, http.ResponseWriter, *http.Request) (interface{}, error)
Давай из хенделера возвращать не пустой интерфейс, а конкретную структуру ответа.

2024-03-04 07:35 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +		response, err := handler.ServeHTTP(ctx, w, r)
Зам объект запроса на всякий случай можно прокинуть в контекст

2024-03-04 08:46 UTC, GeorgiyX requested changes

2024-03-04 08:46 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +		ctx = context.WithValue(ctx, "requestPathParams", pathParams)
requestPathParams  стоит вынести в константу и завести метод GetPathPatamsFromCtx и SetPathParamsToCtx

2024-03-04 08:46 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +		err := json.NewDecoder(limitedReader).Decode(&requestData)
Надо хотя бы логгировать ошибку

2024-03-04 08:46 UTC, GeorgiyX commented on utils/response/response.go
> +	Data   interface{} `json:"data,omitempty"`
Давай тут тоже уйдем от пустого интерфейса. Обычно если статус код отличается от 200, то это ошибка и инфа о статус коде записывается в ошибку. Так что и текст ошибки и статус код можно переложить на второй возвращаемый параметр хендлеров - `error`. Для этого можно определить свой тип ошибки (со статус кодом и текстом ошибки) и проверять во враппере ошибку на этот тип через `errors.As`.

2024-03-05 12:26 UTC, GeorgiyX commented on utils/errors/errors.go
> +	errInternalBytes = []byte("{\n\t\"error\": \"internal error\"\n}")
Чтобы не отражать кавычки (`\"`) можно использовать форму записи строк с обратными одиночными кавычками: `{"error": "text"}`

2024-03-05 12:31 UTC, GeorgiyX commented on utils/errors/errors.go
> +		w.Write(errInternalBytes)
`Write` возвращает ошибку, нужно ее хотя логгировать

2024-03-05 12:32 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +	if err := requestData.Validate(); err != nil {
Переменная `err` уже существует, вместо `:=` стоит использовать `=`

2024-03-05 12:33 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +	// }
Ошибку нужно обработать (хотя бы залогировать)

2024-03-05 12:34 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +	response, err := w.ServeHTTP(ctx, requestData)
Зачем кладем `requestData` и в контекст и передаем в `ServeHTTP`

2024-03-05 12:35 UTC, GeorgiyX approved these changes

2024-03-05 22:51 UTC, GeorgiyX commented on utils/wrapper/wrapper.go
> +	response, err := w.ServeHTTP(ctx)
[Тут](https://github.com/go-park-mail-ru/2024_1_ResCogitans/pull/3#discussion_r1512753537) имел в виду что в в контекст нет необходимости писать requestData, а лучше передавать явно в хендлер.

2024-03-05 22:52 UTC, GeorgiyX approved these changes

2024-03-05 22:54 UTC, sp20ks commented on utils/wrapper/wrapper.go
> +	response, err := w.ServeHTTP(ctx)
балин, у ребят уже ручки авторизации завязаны на requestData из ctx. мы можем это оставить на правку после рк?

2024-03-05 23:04 UTC, merged